include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_annotating_with_dynamic: true
    avoid_catching_errors: true
    avoid_dynamic_calls: true
    avoid_field_initializers_in_const_classes: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: false
    cascade_invocations: false
    cast_nullable_to_non_nullable: true
    discarded_futures: true
    join_return_with_assignment: true
    noop_primitive_operations: true
    omit_local_variable_types: true
    parameter_assignments: true
    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_int_literals: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    unawaited_futures: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    unnecessary_raw_strings: true
    use_named_constants: true
    use_super_parameters: true